CarStoreWeb/Components/DeleteEditButtonViewComponent.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using System;
using System.Threading.Tasks;

namespace CarStoreWeb.Components
{
    public class DeleteEditButtonViewComponent : ViewComponent
    {
        public async Task<IViewComponentResult> InvokeAsync(bool IsAuthorized)
        {
            if (IsAuthorized)
                return View();
            else
                return await Task.FromResult<IViewComponentResult>(Content(string.Empty));
        }
    }
}

CarStoreWeb/Components/LoginStatusViewComponent.cs
using CarStoreWeb.Infrastructure;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;

namespace CarStoreWeb.Components
{
    public class LoginStatusViewComponent:ViewComponent
    {
        private SignInManager<IdentityUser> _signInManager;
        private UserManager<IdentityUser> _userManager;

        public LoginStatusViewComponent(SignInManager<IdentityUser> signInManager, UserManager<IdentityUser> userManager)
        {
            _signInManager = signInManager;
            _userManager = userManager;
        }

        public async Task<IViewComponentResult> InvokeAsync()
        {
            if (_signInManager.IsSignedIn(HttpContext.User))
            {
                var user = await _userManager.GetUserAsync(HttpContext.User);

                if (HttpContext.User.IsInRole("Admin"))
                    return View("AdminLoggedIn", user);
                else
                    return View("LoggedIn", user);
            }
            else
            {
                var returnUrl = HttpContext.Request?.PathAndQuery();
                return View("Default", returnUrl);
            }
        }
    }
}

CarStoreWeb/Components/NavigationMenuViewComponent.cs
using CarStoreWeb.Models;
using CarStoreWeb.Models.ViewModels;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace CarStoreWeb.Components
{
    public class NavigationMenuViewComponent : ViewComponent
    {
        private ICarRepository _repository;
        public NavigationMenuViewComponent(ICarRepository repo)
        {
            _repository = repo;
        }
        
        public async Task<IViewComponentResult> InvokeAsync()
        {
            var cars = await _repository.GetCarsAsync();
            return View(new NavigationMenuViewComponentViewModel()
            {
                Categories = cars.Select(x => x.Brand)
                                             .OrderBy(x => x)
                                             .GroupBy(x => x)
                                             .ToDictionary(x => x.Key, x => x.Count()),
                CurrentCategory = RouteData?.Values["category"]?.ToString()
            }); ; 
        }
    }
}

CarStoreWeb/Views/Shared/NoticeSummary.cshtml
@model CarViewModel
    <div class="bg-white rounded pl-3 pr-3 pt-2 pb-1 mb-2">
        <h3>
            <strong>@Model.Brand</strong>
            <strong>@Model.Model</strong>
            <span class="pull-right label label-primary">
                @Model.Price?.ToString("c", new CultureInfo("en-US"))
            </span>
        </h3>
        <ul class="mb-0">
            <li>Year Of Manufacture: @Model.CarDescription.YearOfManufacture</li>
            <li>Color: @Model.CarDescription.Color</li>
            <li>Fuel Type: @Model.CarDescription.FuelType</li>
            <li>Engine Capacity: @Model.CarDescription.EngineСapacity</li>
        </ul>   
            <div class="mb-2">
                <strong>Contact: @Model.MobileNumber</strong>
                @await Component.InvokeAsync("DeleteEditButton", new { IsAuthorized = Model.IsAuthorized })
            </div>
    </div>


          

CarStoreWeb/Views/Shared/_AdminLayout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>CarStore</title>
    <link rel="stylesheet" asp-href-include="lib/bootstrap/dist/css/*" />
    <link rel="stylesheet" asp-href-include="lib/font-awesome/css/*" />
    <link rel="stylesheet" asp-href-include="css/myStyles.css" />

    <script asp-src-include="lib/jquery/jquery.js"></script>
    <script asp-src-include="lib/bootstrap/dist/js/*.js"></script>
    <style>
        .input-validation-error {
            border-color: red;
            background-color: #fee
        }
    </style>
</head>

<body>
    <div class="container" >
        <div class="row align-items-center" >
            <div class="col-lg-6 mx-auto">
                <div class="jumbotron" style="background-color:transparent;">
                    @RenderBody()
                </div>
            </div>
        </div>
    
    </div>
</body>
</html>

CarStoreWeb/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>CarStore</title>
    <link rel="stylesheet" asp-href-include="lib/bootstrap/dist/css/*" />
    <link rel="stylesheet" asp-href-include="lib/font-awesome/css/*" />
    <link rel="stylesheet" asp-href-include="css/myStyles.css" />

    <script asp-src-include="lib/jquery/jquery.js"></script>
    <script asp-src-include="lib/bootstrap/dist/js/*.js"></script>
    <style>
        .input-validation-error {
            border-color: red;
            background-color: #fee
        }
    </style>
</head>
<body>
    <div class="container-fluid px-md-5 font-italic">
        <nav class="navbar navbar-expand-lg navbar-light bg-white py-3 shadow-sm rounded mb-3">
            <div class="col-lg-6">
                <a href="#" class="navbar-brand">
                    <img src="~/img/logo.jpg" alt="Logo" class="img-thumbnail" style="width:50px;">
                    CAR store
                </a>
            </div>
            <div class="col-lg-6">
                <div class="float-lg-right">
                    @await Component.InvokeAsync("LoginStatus")
                </div>
            </div>
        </nav>

        <div class="row">
            <div class="col-lg-4 mb-4 mt-2 rounded">
                @await Component.InvokeAsync("NavigationMenu")
            </div>

            <div class="col-lg-8 mb-4 rounded">
                <div>
                    <div class="bg-white rounded pl-3 pr-3 pt-0 pb-10 mb-2 mt-2"><strong>@TempData["message"]</strong></div>
                    @RenderBody()
                </div>
            </div>
        </div>
    </div>
</body>
</html>

<!--<ul class="navbar-nav">
                            <li class="dropdown pull-right">
                                <a data-toggle="dropdown" aria-expanded="false" href="#" class="nav-link ">
                                <span class="navbar-toggler-icon"></span>
                                </a>

                        <div role="menu" class="dropdown-menu dropdown-menu-right">
                        <a role="presentation" href="#" class="dropdown-item">About</a>
                        <a role="presentation" href="#" class="dropdown-item">Reserve</a>
                        </div>
                            </li>
                            </ul>-->